### ISSUE TITLE
Failed to Deploy chaincode

### ISSUE THREAD

**Issue by MHamza81** [IBM-Blockchain/SDK-Demo#15]
Hi all,

I am having the following error. 
![capture](https://cloud.githubusercontent.com/assets/11178617/20335590/98942d86-abe5-11e6-8be9-515a7d6edf36.JPG)

I have followed all the steps provided in the README.md file. I have checked the hfc version which is 0.6.5, I have tried by creating a new service on bluemix as it is mentioned that new network uses fabric version 0.6. Please tell me why am I facing this issue and help me solve it. 
Thanks

**Comment by masterDev1985** [comment]
@MHamza81 This is because you don't have a `/tmp` folder on your hard drive.  Create a folder at `C:\tmp` and give the demo another try.

**Comment by MHamza81** [comment]
Thanks. It worked

**Comment by masterDev1985** [comment]
I've added a check for this folder in my fork of the code.  Will close once I've merged that in.

**Comment by masterDev1985** [comment]
No problem!
