### ISSUE TITLE
 Security handshake failed: Failed to deploy chaincode

### ISSUE THREAD

**Issue by d-chau** [IBM-Blockchain/SDK-Demo#16]
`Enrolled admin sucecssfully`

`Enrolled and registered JohnDoe successfully`

`Deploying chaincode ...
E1116 09:50:44.413000000  3360 handshake.c:128] Security handshake failed: {"cre
ated":"@1479307844.413000000","description":"Handshake read failed","file":"..\s
rc\core\lib\security\transport\handshake.c","file_line":237,"referenced_errors":
[{"created":"@1479307844.413000000","description":"End of TCP stream","file":"..
\src\core\lib\iomgr\tcp_windows.c","file_line":180}]}`

`Failed to deploy chaincode: request={"fcn":"init","args":["a","100","b","200"],"
chaincodePath":"chaincode","certificatePath":"/certs/peer/cert.pem"}, error={"er
ror":{"code":14,"metadata":{"_internal_repr":{}}},"msg":"Error"}`

Running hfc0.6.5 and node -v  6.9.1 and grpc 1.0.0 and fabric6. Please advise on why I am getting this error and how can I resolve. Thanks

**Comment by d-chau** [comment]
This is because you don't have a /tmp folder on your hard drive. Create a folder at C:\tmp and give the demo another try. credit to @masterDev1985

**Comment by masterDev1985** [comment]
@d-chau I think this might be something different.  We were seeing some issues with communication to our peers this morning, but those seem to have fixed themselves...  I think things started working for you because you happened to create that folder at the same time that the problems cleared up.  ;)

**Comment by d-chau** [comment]
@masterDev1985  I ran it all again without tmp and received the error 

`Failed to deploy chaincode: request={"fcn":"init","args":["a","100","b","200"]," chaincodePath":"chaincode","certificatePath":"/certs/peer/cert.pem"}, error={"error":{},"msg":"Error: Error creating deployment archive [/tmp/deployment-package.tar.gz]: Error: Error on fs.createWriteStream"}`

But not the handshake error, perhaps that is what was fixed by the communicating peers issue... Making a tmp folder seems to work for me.
