### ISSUE TITLE
timeout when deploying chaincode

### ISSUE THREAD

**Issue by smartheye** [IBM-Blockchain/SDK-Demo#17]
The SDK-Demo source didnot call chaincode deploy complete event while chaincode was deployed 

$ node -v
v4.2.6

$ npm -v
4.0.2

$ npm list | grep hfc
`-- hfc@0.6.5

hfc log

  hfc Previously enrolled, [enrollment={"key":"a9e1a5a3344e8c682454f427b6e813777582feaefecf092ceeaa7f869dbbdf91","cert":"3082019830820140a003020102020101300a06082a8648ce3d0403033029310b3009060355040613025553310c300a060355040a130349424d310c300a06035504031303656361301e170d3136313132313132303432375a170d3137303231393132303432375a3032310b3009060355040613025553310c300a060355040a130349424d3115301306035504030c0c61646d696e5c67726f7570313059301306072a8648ce3d020106082a8648ce3d030107034200041f8119f79537882073638d5eaa1c2a2b76927a4bf1da2497185dd53e71236b47fbad914984cecaae677ce901b9327094d5bd7084d855a9ad1148ebe2b70a5cf6a350304e300e0603551d0f0101ff040403020780300c0603551d130101ff04023000300d0603551d0e0406040401020304300f0603551d2304083006800401020304300e06065103040506070101ff040131300a06082a8648ce3d0403030346003043021f51a445033013d8aedc95409f1f835fd5ba8ba136517187216f31ae8e3529070220133a32c80fa8ab7d2cf2f46fbeabb6800aee7c2784aec4fe120b34cd55b9705e","chainKey":"2d2d2d2d2d424547494e204543445341205055424c4943204b45592d2d2d2d2d0a4d466b77457759484b6f5a497a6a3043415159494b6f5a497a6a304441516344516741454d7939743546346375624f526a57302b494d4b704b6254562f344a620a4c7a566377595965683365686251305343634e676f786f4c46756272454b6a444963617965766431464668306c5773487437636531672f457a673d3d0a2d2d2d2d2d454e44204543445341205055424c4943204b45592d2d2d2d2d0a","queryStateKey":{"type":"Buffer","data":[172,6,92,196,20,253,157,14,206,30,140,126,196,54,175,198,90,23,58,40,46,98,145,229]}}] +0ms

Enrolled admin sucecssfully
  hfc already enrolled +3ms

Enrolled and registered JohnDoe successfully

Deploying chaincode ...
  hfc Member.deploy +3ms
  hfc TransactionContext.deploy +0ms
  hfc Received deploy request: {"fcn":"init","args":["a","100","b","200"],"chaincodePath":"chaincode","certificatePath":"/certs/peer/cert.pem"} +1ms
  hfc [TransactionContext] No TCert cached. Retrieving one. +0ms
  hfc Member.getNextTCert: key=null +0ms
  hfc Member.getNextTCert: key=null, creating new getter +0ms
  hfc shouldGetTCerts: yes, we have no tcerts +2ms
  hfc Warning: problem parsing certificate bytes; retrying ...  [RangeError: byte length of Uint32Array should be a multiple of 4] +3s
  hfc Got a TCert successfully, continue... +1s
  hfc newBuildOrDeployTransaction +0ms
  hfc newNetModeTransaction +1ms
  hfc $GOPATH: hyperledger-dev\fabric-dev\client\nodejs\IBM-SDK-Demo +0ms
  hfc projDir: SDK-Demo/src/chaincode +0ms
  hfc GenerateParameterHash... +0ms
  hfc path: chaincode +0ms
  hfc func: init +0ms
  hfc args: a,100,b,200 +0ms
  hfc str: chaincodeinita100b200 +0ms
  hfc strHash: 9917933edde33368e8725555a00183d9d4d3d3eb8231270f96f0cf6937e75438 +0ms
  hfc hash: bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe +3s
  hfc type of request.certificatePath: string +0ms
  hfc request.certificatePath: /certs/peer/cert.pem +0ms
  hfc Adding COPY certificate.pem command +0ms
  hfc Created Dockerfile at [hyperledger-dev\fabric-dev\client\nodejs\IBM-SDK-Demo/src/chaincode/Dockerfile] +3ms
  hfc GenerateTarGz +0ms
  hfc Created deployment archive at [/tmp/deployment-package.tar.gz] +2s
  hfc chaincodeID: {"path":"","name":"bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe"} +3ms
  hfc chaincodeSpec: {"type":1,"chaincodeID":{"path":"","name":"bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe"},"ctorMsg":{"args":[{"buffer":{"type":"Buffer","data":[105,110,105,116]},"offset":0,"markedOffset":-1,"limit":4,"littleEndian":false,"noAssert":false},{"buffer":{"type":"Buffer","data":[97]},"offset":0,"markedOffset":-1,"limit":1,"littleEndian":false,"noAssert":false},{"buffer":{"type":"Buffer","data":[49,48,48]},"offset":0,"markedOffset":-1,"limit":3,"littleEndian":false,"noAssert":false},{"buffer":{"type":"Buffer","data":[98]},"offset":0,"markedOffset":-1,"limit":1,"littleEndian":false,"noAssert":false},{"buffer":{"type":"Buffer","data":[50,48,48]},"offset":0,"markedOffset":-1,"limit":3,"littleEndian":false,"noAssert":false}]},"timeout":0,"secureContext":"","confidentialityLevel":0,"metadata":{"buffer":{"type":"Buffer","data":[]},"offset":0,"markedOffset":-1,"limit":0,"littleEndian":false,"noAssert":false},"attributes":[]} +4ms
  hfc Read in deployment archive from [/tmp/deployment-package.tar.gz] +5ms
  hfc Set confidentiality level to PUBLIC +20ms
  hfc Temporary archive deleted successfully ---> /tmp/deployment-package.tar.gz +1ms
  hfc File deleted successfully ---> \hyperledger-dev\fabric-dev\client\nodejs\IBM-SDK-Demo/src/chaincode/Dockerfile +1ms
  hfc Calling TransactionContext.execute +1ms
  hfc Executing transaction +0ms
  hfc [TransactionContext] TCert already cached. +0ms
  hfc Process Confidentiality... +1ms
  hfc Sign transaction... +1ms
  hfc Send transaction... +106ms
  hfc Confidentiality:  0 +0ms
  hfc reg txid bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe +0ms
  hfc waiting 300 seconds before emitting complete event +5ms
  hfc peer.sendTransaction +262ms
  hfc peer.sendTransaction: received {"status":"SUCCESS","msg":{"type":"Buffer","data":[98,99,51,55,55,50,56,53,50,100,56,49,50,99,100,99,55,100,98,102,53,51,55,49,102,98,102,55,48,98,56,100,49,100,101,99,48,52,51,48,55,100,52,52,56,50,56,53,51,52,53,56,50,100,100,55,54,51,57,56,57,56,102,101]}} +25s
  hfc EventDeploySubmitted event: {"uuid":"bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe","chaincodeID":"bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe"} +0ms
  hfc txCallback event={"version":0,"timestamp":null,"transactions":[],"stateHash":{"type":"Buffer","data":[89,202,116,243,192,129,33,110,122,107,213,132,112,187,33,144,231,175,64,121,255,62,60,117,45,110,100,8,142,184,172,40,237,177,49,33,218,72,138,96,198,240,140,75,64,212,106,237,73,134,110,54,55,183,40,66,129,207,48,44,35,91,86,116]},"previousBlockHash":{"type":"Buffer","data":[232,255,109,54,234,159,8,227,131,133,34,208,223,244,19,8,154,161,122,72,63,246,109,26,124,57,238,252,139,125,149,9,199,159,126,163,34,143,119,37,112,84,92,55,56,125,21,132,240,224,30,170,201,15,188,32,146,29,122,89,237,88,242,104]},"consensusMetadata":{"type":"Buffer","data":[8,3]},"nonHashData":{"localLedgerCommitTimestamp":{"seconds":"1479731321","nanos":633872811},"chaincodeEvents":[{"chaincodeID":"","txID":"","eventName":"","payload":{"type":"Buffer","data":[]}}]}} +1s
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: {"created":"@1479817938.867000000","description":"Secure read failed","file":"..\src\core\lib\security\transport\secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1479817938.867000000","description":"An existing connection was forcibly closed by the remote host.\r\n","file":"..\src\core\lib\iomgr\tcp_windows.c","file_line":171}]}
    at ClientDuplexStream._emitStatusIfDone (SDK-Demo\node_modules\grpc\src\node\src\client.js:189:19)
    at ClientDuplexStream._receiveStatus (SDK-Demo\node_modules\grpc\src\node\src\client.js:169:8)
    at SDK-Demo\node_modules\grpc\src\node\src\client.js:634:14

Process finished with exit code 1

**Comment by ratnakar-asara** [comment]
@smartheye You will see this issue when you try deploy the chaincode which has been deployed already.
Could you see if **chaincodeID** file exists in your directory.
If that doesn't exists could you create a file name with chaincode ID and update it with the actual chaincode ID `bc3772852d812cdc7dbf5371fbf70b8d1dec04307d44828534582dd7639898fe` and re-run the program.

**Comment by smartheye** [comment]
@ratnakar-asara
Thanks. yes, it's the reason. Is it possible to query whether the chaincode has been deployed without knowing the chaincode ID.

**Comment by sibelius** [comment]
@ratnakar-asara how can I redeploy a chaincode? chaincode ID exists already. but my chaincode changed
