### ISSUE TITLE
ClientDuplexStream._emitStatusIfDone on connecting bluemix's event hub url

### ISSUE THREAD

**Issue by smartheye** [IBM-Blockchain/SDK-Demo#20]
while executing the following source:

chain.eventHubConnect(eventUrls[0], {
        pem: cert
});

the errors happens:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (C:\DEV\workplace\fabric-connector\node_modules\grpc\src\node\src\client.js:189:19)
    at ClientDuplexStream._readsDone (C:\DEV\workplace\fabric-connector\node_modules\grpc\src\node\src\client.js:158:8)
    at readCallback (C:\DEV\workplace\fabric-connector\node_modules\grpc\src\node\src\client.js:217:12)

is there any walkaround or just bluemix is unstable?

**Comment by smartheye** [comment]
the full log of grpc (sorry a little bit long)


D1226 14:05:31.778000000  9024 connectivity_state.c:92] CONWATCH: 0000000002B84C50 (null): get IDLE
D1226 14:05:31.778000000  9024 connectivity_state.c:156] SET: 0000000002B7D2B8 client_channel: IDLE --> IDLE [new_lb+resolver] error=0000000000000000 null
D1226 14:05:31.778000000  9024 connectivity_state.c:109] CONWATCH: 0000000002B84C50 (null): from IDLE [cur=IDLE] notify=0000000002D3E078
D1226 14:05:31.778000000  9024 connectivity_state.c:109] CONWATCH: 0000000002EA3020 subchannel: from IDLE [cur=IDLE] notify=0000000002D49DC8
D1226 14:05:31.778000000  9024 connectivity_state.c:156] SET: 0000000002EA3020 subchannel: IDLE --> CONNECTING [state_change] error=0000000000000000 null
D1226 14:05:31.778000000  9024 connectivity_state.c:183] NOTIFY: 0000000002D49DC8
D1226 14:05:31.778000000  9024 connectivity_state.c:156] SET: 0000000002B84C50 (null): IDLE --> CONNECTING [connecting_changed] error=0000000000000000 null
D1226 14:05:31.778000000  9024 connectivity_state.c:183] NOTIFY: 0000000002D3E078
D1226 14:05:31.778000000  9024 connectivity_state.c:109] CONWATCH: 0000000002EA3020 subchannel: from CONNECTING [cur=CONNECTING] notify=0000000002D49DC8
D1226 14:05:31.778000000  9024 connectivity_state.c:156] SET: 0000000002B7D2B8 client_channel: IDLE --> CONNECTING [lb_changed] error=0000000000000000 null
D1226 14:05:31.778000000  9024 connectivity_state.c:109] CONWATCH: 0000000002B84C50 (null): from CONNECTING [cur=CONNECTING] notify=0000000002D3E238
I1226 14:05:31.882000000 12116 channel.c:231] grpc_channel_create_call(channel=0000000002B7C7A0, parent_call=0000000000000000, propagation_mask=ffff, cq=00000000003970A0, method=/protos.TCAP/CreateCertificateSet, host=(null), deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0000000000000000)
I1226 14:05:31.882000000 12116 metadata_array.c:42] grpc_metadata_array_init(array=000000000017E730)
I1226 14:05:31.883000000 12116 metadata_array.c:42] grpc_metadata_array_init(array=0000000002D3D778)
I1226 14:05:31.883000000 12116 metadata_array.c:42] grpc_metadata_array_init(array=0000000002D30DC8)
I1226 14:05:31.883000000 12116 call.c:1690] grpc_call_start_batch(call=0000000002D2FF70, ops=0000000002D30880, nops=6, tag=0000000002D3D7A0, reserved=0000000000000000)
I1226 14:05:31.883000000 12116 call.c:1366] ops[0]: SEND_INITIAL_METADATA
I1226 14:05:31.883000000 12116 call.c:1366] ops[1]: SEND_MESSAGE ptr=0000000002B75BB0
I1226 14:05:31.883000000 12116 call.c:1366] ops[2]: SEND_CLOSE_FROM_CLIENT
I1226 14:05:31.883000000 12116 call.c:1366] ops[3]: RECV_INITIAL_METADATA ptr=0000000002D3D778
I1226 14:05:31.883000000 12116 call.c:1366] ops[4]: RECV_MESSAGE ptr=0000000002C73AB8
I1226 14:05:31.883000000 12116 call.c:1366] ops[5]: RECV_STATUS_ON_CLIENT metadata=0000000002D30DC8 status=0000000002D30DE0 details=0000000002D30DE8
I1226 14:05:31.883000000 12116 client_channel.c:109] OP[client-channel:0000000002D30580]: SEND_INITIAL_METADATA{key=3a 70 61 74 68 ':path' value=2f 70 72 6f 74 6f 73 2e 54 43 41 50 2f 43 72 65 61 74 65 43 65 72 74 69 66 69 63 61 74 65 53 65 74 '/protos.TCAP/CreateCertificateSet', key=3a 61 75 74 68 6f 72 69 74 79 ':authority' value=31 62 37 37 30 39 61 36 65 30 34 31 34 38 66 61 39 30 34 38 33 64 39 64 62 39 62 33 31 65 38 33 2d 63 61 2e 75 73 2e 62 6c 6f 63 6b 63 68 61 69 6e 2e 69 62 6d 2e 63 6f 6d 3a 33 30 30 30 32 '1b7709a6e04148fa90483d9db9b31e83-ca.us.blockchain.ibm.com:30002', key=67 72 70 63 2d 65 6e 63 6f 64 69 6e 67 'grpc-encoding' value=69 64 65 6e 74 69 74 79 'identity', key=67 72 70 63 2d 61 63 63 65 70 74 2d 65 6e 63 6f 64 69 6e 67 'grpc-accept-encoding' value=69 64 65 6e 74 69 74 79 2c 64 65 66 6c 61 74 65 2c 67 7a 69 70 'identity,deflate,gzip'} SEND_MESSAGE:flags=0x00000000:len=184 SEND_TRAILING_METADATA{} RECV_INITIAL_METADATA RECV_MESSAGE RECV_TRAILING_METADATA
D1226 14:05:32.359000000  2616 connectivity_state.c:92] CONWATCH: 0000000002B84D20 (null): get IDLE
D1226 14:05:32.360000000  2616 connectivity_state.c:156] SET: 0000000002B7C8F8 client_channel: IDLE --> IDLE [new_lb+resolver] error=0000000000000000 null
D1226 14:05:32.360000000  2616 connectivity_state.c:109] CONWATCH: 0000000002B84D20 (null): from IDLE [cur=IDLE] notify=0000000002D3DC38
D1226 14:05:32.360000000  2616 connectivity_state.c:109] CONWATCH: 0000000002EA2E50 subchannel: from IDLE [cur=IDLE] notify=0000000002D49E68
D1226 14:05:32.360000000  2616 connectivity_state.c:156] SET: 0000000002EA2E50 subchannel: IDLE --> CONNECTING [state_change] error=0000000000000000 null
D1226 14:05:32.360000000  2616 connectivity_state.c:183] NOTIFY: 0000000002D49E68
D1226 14:05:32.361000000  2616 connectivity_state.c:156] SET: 0000000002B84D20 (null): IDLE --> CONNECTING [connecting_changed] error=0000000000000000 null
D1226 14:05:32.361000000  2616 connectivity_state.c:183] NOTIFY: 0000000002D3DC38
D1226 14:05:32.361000000  2616 connectivity_state.c:109] CONWATCH: 0000000002EA2E50 subchannel: from CONNECTING [cur=CONNECTING] notify=0000000002D49E68
D1226 14:05:32.361000000  2616 connectivity_state.c:156] SET: 0000000002B7C8F8 client_channel: IDLE --> CONNECTING [lb_changed] error=0000000000000000 null
D1226 14:05:32.361000000  2616 connectivity_state.c:109] CONWATCH: 0000000002B84D20 (null): from CONNECTING [cur=CONNECTING] notify=0000000002D3E438
I1226 14:05:32.608000000 11620 ssl_transport_security.c:191]      HANDSHAKE START -  before connect initialization  - CINIT 
I1226 14:05:32.608000000 11620 ssl_transport_security.c:191]                 LOOP -  before connect initialization  - CINIT 
I1226 14:05:32.609000000 11620 ssl_transport_security.c:191]                 LOOP -     SSLv3 write client hello A  - 3WCH_A
D1226 14:05:32.778000000 11620 connectivity_state.c:156] SET: 0000000002EA3020 subchannel: CONNECTING --> TRANSIENT_FAILURE [connect_failed] error=0000000002CF5A20 {"created":"@1482732332.778000000","description":"Connect Failed","file":"..\src\core\ext\client_config\subchannel.c","file_line":638}
D1226 14:05:32.778000000 11620 connectivity_state.c:183] NOTIFY: 0000000002D49DC8
I1226 14:05:32.778000000 11620 subchannel.c:642] Connect failed: null
I1226 14:05:32.778000000 11620 subchannel.c:645] Retry immediately
D1226 14:05:32.778000000 11620 connectivity_state.c:156] SET: 0000000002B84C50 (null): CONNECTING --> TRANSIENT_FAILURE [connecting_transient_failure] error=0000000002CF5A20 {"created":"@1482732332.778000000","description":"Connect Failed","file":"..\src\core\ext\client_config\subchannel.c","file_line":638}
D1226 14:05:32.778000000 11620 connectivity_state.c:183] NOTIFY: 0000000002D3E238
D1226 14:05:32.778000000 11620 connectivity_state.c:92] CONWATCH: 0000000002EA3020 subchannel: get TRANSIENT_FAILURE
D1226 14:05:32.778000000 11620 connectivity_state.c:109] CONWATCH: 0000000002EA3020 subchannel: from TRANSIENT_FAILURE [cur=TRANSIENT_FAILURE] notify=0000000002D49DC8
I1226 14:05:32.778000000 11620 subchannel.c:609] Failed to connect to channel, retrying
D1226 14:05:32.778000000 11620 connectivity_state.c:156] SET: 0000000002EA3020 subchannel: TRANSIENT_FAILURE --> CONNECTING [state_change] error=0000000000000000 null
D1226 14:05:32.778000000 11620 connectivity_state.c:183] NOTIFY: 0000000002D49DC8
D1226 14:05:32.778000000 11620 connectivity_state.c:156] SET: 0000000002B7D2B8 client_channel: CONNECTING --> TRANSIENT_FAILURE [lb_changed] error=0000000002CF5A20 {"created":"@1482732332.778000000","description":"Connect Failed","file":"..\src\core\ext\client_config\subchannel.c","file_line":638}
D1226 14:05:32.778000000 11620 connectivity_state.c:109] CONWATCH: 0000000002B84C50 (null): from TRANSIENT_FAILURE [cur=TRANSIENT_FAILURE] notify=0000000002D3E678
D1226 14:05:32.778000000 11620 connectivity_state.c:156] SET: 0000000002B84C50 (null): TRANSIENT_FAILURE --> CONNECTING [connecting_changed] error=0000000000000000 null
D1226 14:05:32.778000000 11620 connectivity_state.c:183] NOTIFY: 0000000002D3E678
D1226 14:05:32.778000000 11620 connectivity_state.c:109] CONWATCH: 0000000002EA3020 subchannel: from CONNECTING [cur=CONNECTING] notify=0000000002D49DC8
D1226 14:05:32.778000000 11620 connectivity_state.c:156] SET: 0000000002B7D2B8 client_channel: TRANSIENT_FAILURE --> CONNECTING [lb_changed] error=0000000000000000 null
D1226 14:05:32.778000000 11620 connectivity_state.c:109] CONWATCH: 0000000002B84C50 (null): from CONNECTING [cur=CONNECTING] notify=0000000002D3E578
I1226 14:05:32.779000000 11620 completion_queue.c:252] grpc_cq_end_op(exec_ctx=00000000035EF930, cc=00000000003970A0, tag=0000000002D3D200, error={"created":"@1482732332.778000000","description":"Failed to create subchannel","file":"..\src\core\ext\client_config\subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482732332.778000000","description":"Pick Cancelled","file":"..\src\core\ext\lb_policy\pick_first\pick_first.c","file_line":170}]}, done=000007FED6F94B60, done_arg=0000000002C770D0, storage=0000000002C770D8)
E1226 14:05:32.779000000 11620 completion_queue.c:254] Operation failed: tag=0000000002D3D200, error={"created":"@1482732332.778000000","description":"Failed to create subchannel","file":"..\src\core\ext\client_config\subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482732332.778000000","description":"Pick Cancelled","file":"..\src\core\ext\lb_policy\pick_first\pick_first.c","file_line":170}]}
I1226 14:05:32.779000000 11620 completion_queue.c:252] grpc_cq_end_op(exec_ctx=00000000035EF930, cc=00000000003970A0, tag=0000000002D3D650, error=null, done=000007FED6F94B60, done_arg=0000000002C77138, storage=0000000002C77140)
I1226 14:05:32.779000000 12724 completion_queue.c:394] RETURN_EVENT[00000000003970A0]: OP_COMPLETE: tag:0000000002D3D200 ERROR
I1226 14:05:32.779000000 11620 completion_queue.c:252] grpc_cq_end_op(exec_ctx=00000000035EF930, cc=00000000003970A0, tag=0000000002D3D680, error={"created":"@1482732332.778000000","description":"Failed to create subchannel","file":"..\src\core\ext\client_config\subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482732332.778000000","description":"Pick Cancelled","file":"..\src\core\ext\lb_policy\pick_first\pick_first.c","file_line":170}]}, done=000007FED6F94B60, done_arg=0000000002C771A0, storage=0000000002C771A8)
E1226 14:05:32.779000000 11620 completion_queue.c:254] Operation failed: tag=0000000002D3D680, error={"created":"@1482732332.778000000","description":"Failed to create subchannel","file":"..\src\core\ext\client_config\subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482732332.778000000","description":"Pick Cancelled","file":"..\src\core\ext\lb_policy\pick_first\pick_first.c","file_line":170}]}
I1226 14:05:32.779000000 11620 completion_queue.c:252] grpc_cq_end_op(exec_ctx=00000000035EF930, cc=00000000003970A0, tag=0000000002BD8050, error={"created":"@1482732332.778000000","description":"Failed to create subchannel","file":"..\src\core\ext\client_config\subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482732332.778000000","description":"Pick Cancelled","file":"..\src\core\ext\lb_policy\pick_first\pick_first.c","file_line":170}]}, done=000007FED6F94B60, done_arg=0000000002C77208, storage=0000000002C77210)
E1226 14:05:32.779000000 11620 completion_queue.c:254] Operation failed: tag=0000000002BD8050, error={"created":"@1482732332.778000000","description":"Failed to create subchannel","file":"..\src\core\ext\client_config\subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482732332.778000000","description":"Pick Cancelled","file":"..\src\core\ext\lb_policy\pick_first\pick_first.c","file_line":170}]}
I1226 14:05:32.779000000 11620 completion_queue.c:394] RETURN_EVENT[00000000003970A0]: OP_COMPLETE: tag:0000000002D3D650 OK
I1226 14:05:32.779000000 11620 completion_queue.c:333] grpc_completion_queue_next(cc=00000000003970A0, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0000000000000000)
I1226 14:05:32.779000000 11620 completion_queue.c:394] RETURN_EVENT[00000000003970A0]: OP_COMPLETE: tag:0000000002D3D680 ERROR
I1226 14:05:32.779000000 12116 metadata_array.c:47] grpc_metadata_array_destroy(array=0000000002D3D298)
I1226 14:05:32.779000000  2200 completion_queue.c:333] grpc_completion_queue_next(cc=00000000003970A0, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0000000000000000)
I1226 14:05:32.779000000  2200 completion_queue.c:394] RETURN_EVENT[00000000003970A0]: OP_COMPLETE: tag:0000000002BD8050 ERROR
I1226 14:05:32.779000000 12116 metadata_array.c:47] grpc_metadata_array_destroy(array=0000000002D3DBF8)
I1226 14:05:32.779000000 12724 completion_queue.c:333] grpc_completion_queue_next(cc=00000000003970A0, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0000000000000000)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (C:\DEV\workplace\fabric-connector\node_modules\grpc\src\node\src\client.js:189:19)
    at ClientDuplexStream._readsDone (C:\DEV\workplace\fabric-connector\node_modules\grpc\src\node\src\client.js:158:8)
    at readCallback (C:\DEV\workplace\fabric-connector\node_modules\grpc\src\node\src\client.js:217:12)

**Comment by mastersingh24** [comment]
is your event port 30001?

**Comment by jonathan-yk-tan** [comment]
I have a similar error : 

jonathans-mbp:SDK-Demo Jonathan$ node helloblockchain.js

------------- ca-server, peers and event URL:PORT information: -------------

CA server Url : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-ca.us.blockchain.ibm.com:30001

Validating Peer0 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp3.us.blockchain.ibm.com:30001
Validating Peer1 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp2.us.blockchain.ibm.com:30001
Validating Peer2 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp1.us.blockchain.ibm.com:30001
Validating Peer3 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp0.us.blockchain.ibm.com:30001

Event Url on Peer0 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp3.us.blockchain.ibm.com:31001
Event Url on Peer1 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp2.us.blockchain.ibm.com:31001
Event Url on Peer2 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp1.us.blockchain.ibm.com:31001
Event Url on Peer3 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp0.us.blockchain.ibm.com:31001

-----------------------------------------------------------

E0103 12:52:19.308346000 123145560309760 handshake.c:128] Security handshake failed: {"created":"@1483419139.308311000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1483419139.308306000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/Users/Jonathan/projects/SDK-Demo/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/Users/Jonathan/projects/SDK-Demo/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/Users/Jonathan/projects/SDK-Demo/node_modules/grpc/src/node/src/client.js:217:12)
jonathans-mbp:SDK-Demo Jonathan$ GRPC_TRACE=all DEBUG=hfc node helloblockchain.js

------------- ca-server, peers and event URL:PORT information: -------------

CA server Url : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-ca.us.blockchain.ibm.com:30001

Validating Peer0 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp3.us.blockchain.ibm.com:30001
Validating Peer1 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp2.us.blockchain.ibm.com:30001
Validating Peer2 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp1.us.blockchain.ibm.com:30001
Validating Peer3 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp0.us.blockchain.ibm.com:30001

Event Url on Peer0 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp3.us.blockchain.ibm.com:31001
Event Url on Peer1 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp2.us.blockchain.ibm.com:31001
Event Url on Peer2 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp1.us.blockchain.ibm.com:31001
Event Url on Peer3 : grpcs://ef5bcb0a645d4754a0c1ba0c8eb9366b-vp0.us.blockchain.ibm.com:31001

-----------------------------------------------------------

  hfc Enrolling [req={"enrollmentID":"admin","enrollmentSecret":"b5f5a3b470"}] +0ms
  hfc [MemberServicesImpl.enroll] [{"enrollmentID":"admin","enrollmentSecret":"b5f5a3b470"}] +0ms
  hfc [MemberServicesImpl.enroll] Generating keys... +1ms
  hfc [MemberServicesImpl.enroll] Generating keys...done! +84ms
  hfc [MemberServicesImpl.enroll] Generating request! "3059301306072a8648ce3d020106082a8648ce3d030107034200046cf57b68a0c414f37935590c0c53f3d632a07074847835cde8bc41f65e22749fb8b0719ceecb25ed6a867de71c434d817327da9242ad5189de7560b6d6fd876d" +1ms
  hfc [MemberServicesImpl.enroll] Adding signing key! +1ms
  hfc [MemberServicesImpl.enroll] Assding encryption key! +0ms
  hfc [MemberServicesImpl.enroll] [Contact ECA] {"ts":{"seconds":{"low":1483419159,"high":0,"unsigned":false},"nanos":0},"id":{"id":"admin"},"tok":{"tok":{"buffer":{"type":"Buffer","data":[98,53,102,53,97,51,98,52,55,48]},"offset":0,"markedOffset":-1,"limit":10,"littleEndian":false,"noAssert":false}},"sign":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,108,245,123,104,160,196,20,243,121,53,89,12,12,83,243,214,50,160,112,116,132,120,53,205,232,188,65,246,94,34,116,159,184,176,113,156,238,203,37,237,106,134,125,231,28,67,77,129,115,39,218,146,66,173,81,137,222,117,96,182,214,253,135,109]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"enc":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,60,109,111,240,53,190,181,128,140,210,252,80,146,228,143,118,85,38,191,77,122,167,85,233,64,126,128,220,54,88,199,39,214,68,193,183,23,77,22,235,175,217,185,197,140,7,247,110,48,141,175,246,142,43,206,94,209,41,35,244,61,79,217,122]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"sig":null}  +0ms
E0103 12:52:40.659622000 123145491320832 completion_queue.c:254] Operation failed: tag=0x10480a390, error={"created":"@1483419160.659582000","description":"Failed to create subchannel","file":"../src/core/ext/client_config/subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1483419160.659520000","description":"Pick Cancelled","file":"../src/core/ext/lb_policy/pick_first/pick_first.c","file_line":170}]}
E0103 12:52:40.660039000 123145491320832 completion_queue.c:254] Operation failed: tag=0x10480bdd0, error={"created":"@1483419160.659582000","description":"Failed to create subchannel","file":"../src/core/ext/client_config/subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1483419160.659520000","description":"Pick Cancelled","file":"../src/core/ext/lb_policy/pick_first/pick_first.c","file_line":170}]}
E0103 12:52:40.660078000 123145491320832 completion_queue.c:254] Operation failed: tag=0x104817950, error={"created":"@1483419160.659582000","description":"Failed to create subchannel","file":"../src/core/ext/client_config/subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1483419160.659520000","description":"Pick Cancelled","file":"../src/core/ext/lb_policy/pick_first/pick_first.c","file_line":170}]}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/Users/Jonathan/projects/SDK-Demo/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/Users/Jonathan/projects/SDK-Demo/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/Users/Jonathan/projects/SDK-Demo/node_modules/grpc/src/node/src/client.js:217:12)

**Comment by mrshah-at-work** [comment]
@jonathan-yk-tan is this a consistent error? Did you try running it again and getting the same error?

**Comment by arner** [comment]
Hi @mrshah-at-ibm, I too get this error regularly. Sometimes seemingly out of nowhere, otherwise when registering for an event. Only on bluemix, locally it all works fine. The first time I registered for an event I had no problems, but since the second time I cannot get it to work, even after hard restarts and redeploys of the nodejs app.

**Comment by mrshah-at-work** [comment]
@arner it happens because of a timeout on the proxy sitting in front of the peer. This cannot be removed/resolved. Can you add a periodic activity on the event connection as a work around to this issue?

**Comment by arner** [comment]
Thanks @mrshah-at-ibm, how would you envision this? Do a periodic 'keep-alive' query and let the chaincode 'respond' with an event? How much time should there be between the pings? The thing is, once it stops working I don't know of a way of reviving the connection (re-registering doesn't help).

Secondly, will this issue be resolved when IBM Blockchain moves to Hyperledger V1? I heard it would run on new infrastructure...

**Comment by mrshah-at-work** [comment]
@arner That should work. Keep the 'keep-alive' to less than 120s (60s preferred).

Yes, it should be resolved with the move to Hyperledger V1.

**Comment by arner** [comment]
Thank you! Good to hear.

**Comment by bravera** [comment]
I have a problem like this with Hyperledger V1.
I have followed the instructions at http://hyperledger-fabric.readthedocs.io/en/latest/asset_setup.html on an Ubuntu 14.04 vm I have running in a private cloud infrastructure.

When I run the deploy step `GOPATH=$PWD node deploy.js` I get this error below:

Any suggestions? @mastersingh24 @mrshah-at-ibm 

```info: Returning a new winston logger with default configurations
info: [Chain.js]: Constructed Chain instance: name - fabric-client1, securityEnabled: true, TCert download batch size: 10, network mode: true
info: [Peer.js]: Peer.const - url: grpc://localhost:8051 options  grpc.ssl_target_name_override=tlsca, grpc.default_authority=tlsca
info: [Peer.js]: Peer.const - url: grpc://localhost:8055 options  grpc.ssl_target_name_override=tlsca, grpc.default_authority=tlsca
info: [Peer.js]: Peer.const - url: grpc://localhost:8056 options  grpc.ssl_target_name_override=tlsca, grpc.default_authority=tlsca
info: [Client.js]: Failed to load user "admin" from local key value store
info: [FabricCAClientImpl.js]: Successfully constructed Fabric COP service client: endpoint - {"protocol":"http","hostname":"localhost","port":8054}
info: [crypto_ecdsa_aes]: This class requires a KeyValueStore to save keys, no store was passed in, using the default store /home/fabric/.hfc-key-store
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connect Failed
    at ClientDuplexStream._emitStatusIfDone (/home/fabric/workspace/hackfest/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._readsDone (/home/fabric/workspace/hackfest/node_modules/grpc/src/node/src/client.js:169:8)
    at readCallback (/home/fabric/workspace/hackfest/node_modules/grpc/src/node/src/client.js:229:12)```

**Comment by arun-karthikeyan** [comment]
I have the same issue as @bravera  too, trying to figure out what's wrong but no success. Any help is really appreciated.

**Comment by saurabhxtiwari** [comment]
@arun-karthikeyan @bravera Guys any updates  on how did you get around on this issue. I have been getting this consistently while deploying a composer network to already running fabric.

**Comment by Madssimono** [comment]
Did any of you ever find the issue? I have the same as @bravera and @arun-karthikeyan

**Comment by mrshah-at-work** [comment]
@Madssimono this repository has been archived as fabric & IBM-Blockchain has moved to fabric v1.x.
