### ISSUE TITLE
Security handshake failed in sdk demo failing using hfc@0.6.5

### ISSUE THREAD

**Issue by goupadhy** [IBM-Blockchain/SDK-Demo#21]
We tried running the sample using hfc@0.6.5 for the sdk https://github.com/IBM-Blockchain/SDK-Demo 
------------- ca-server, peers and event URL:PORT information: -------------

CA server Url : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-ca.us.blockchain.ibm.com:30004

Validating Peer0 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp1.us.blockchain.ibm.com:30004
Validating Peer1 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp2.us.blockchain.ibm.com:30004
Validating Peer2 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp3.us.blockchain.ibm.com:30004
Validating Peer3 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp0.us.blockchain.ibm.com:30004

Event Url on Peer0 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp1.us.blockchain.ibm.com:31004
Event Url on Peer1 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp2.us.blockchain.ibm.com:31004
Event Url on Peer2 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp3.us.blockchain.ibm.com:31004
Event Url on Peer3 : grpcs://db9f0dfdd1ce4d7da5bd545f97279e10-vp0.us.blockchain.ibm.com:31004

-----------------------------------------------------------

E1228 15:48:28.887602000 123145307131904 handshake.c:128] Security handshake failed: {"created":"@1482920308.887541000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1482920308.887529000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/Users/goupadhy/work/src/github.com/goupadhy/SDK-Demo/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/Users/goupadhy/work/src/github.com/goupadhy/SDK-Demo/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/Users/goupadhy/work/src/github.com/goupadhy/SDK-Demo/node_modules/grpc/src/node/src/client.js:217:12)
E1228 15:48:29.000124000 123145306595328 handshake.c:128] Security handshake failed: {"created":"@1482920309.000078000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1482920309.000071000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}

**Comment by mastersingh24** [comment]
@goupadhy  - what OS are you running the sample on and which version of NodeJS are you using?

**Comment by goupadhy** [comment]
I'm running on MAC OS version 10.11.6 (15G1212)

**Comment by mastersingh24** [comment]
which version of NodeJS?

**Comment by mastersingh24** [comment]
one more thing which might help us - can you turn on GRPC trace and debug and then post the logs/output again?

`GRPC_TRACE=all GRPC_VERBOSITY=debug node helloblockchain.js`

**Comment by goupadhy** [comment]
------------- ca-server, peers and event URL:PORT information: -------------

CA server Url : grpcs://b5d8132500bc4023be96737d7be92563-ca.us.blockchain.ibm.com:30003

Validating Peer0 : grpcs://b5d8132500bc4023be96737d7be92563-vp3.us.blockchain.ibm.com:30003
Validating Peer1 : grpcs://b5d8132500bc4023be96737d7be92563-vp1.us.blockchain.ibm.com:30003
Validating Peer2 : grpcs://b5d8132500bc4023be96737d7be92563-vp0.us.blockchain.ibm.com:30003
Validating Peer3 : grpcs://b5d8132500bc4023be96737d7be92563-vp2.us.blockchain.ibm.com:30003

Event Url on Peer0 : grpcs://b5d8132500bc4023be96737d7be92563-vp3.us.blockchain.ibm.com:31003
Event Url on Peer1 : grpcs://b5d8132500bc4023be96737d7be92563-vp1.us.blockchain.ibm.com:31003
Event Url on Peer2 : grpcs://b5d8132500bc4023be96737d7be92563-vp0.us.blockchain.ibm.com:31003
Event Url on Peer3 : grpcs://b5d8132500bc4023be96737d7be92563-vp2.us.blockchain.ibm.com:31003

-----------------------------------------------------------

  hfc Enrolling [req={"enrollmentID":"admin","enrollmentSecret":"2bc0ff4c23"}] +0ms
  hfc [MemberServicesImpl.enroll] [{"enrollmentID":"admin","enrollmentSecret":"2bc0ff4c23"}] +1ms
  hfc [MemberServicesImpl.enroll] Generating keys... +1ms
  hfc [MemberServicesImpl.enroll] Generating keys...done! +94ms
  hfc [MemberServicesImpl.enroll] Generating request! "3059301306072a8648ce3d020106082a8648ce3d0301070342000471cca537fad9b3c047fddc3044076348dd3f5568c658accf065bdaf13f37d3baf8173cb9df1c88ccb665eded7edb5e87e321cd00824b5826b606531245caa912" +4ms
  hfc [MemberServicesImpl.enroll] Adding signing key! +1ms
  hfc [MemberServicesImpl.enroll] Assding encryption key! +0ms
  hfc [MemberServicesImpl.enroll] [Contact ECA] {"ts":{"seconds":{"low":1482927538,"high":0,"unsigned":false},"nanos":0},"id":{"id":"admin"},"tok":{"tok":{"buffer":{"type":"Buffer","data":[50,98,99,48,102,102,52,99,50,51]},"offset":0,"markedOffset":-1,"limit":10,"littleEndian":false,"noAssert":false}},"sign":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,113,204,165,55,250,217,179,192,71,253,220,48,68,7,99,72,221,63,85,104,198,88,172,207,6,91,218,241,63,55,211,186,248,23,60,185,223,28,136,204,182,101,237,237,126,219,94,135,227,33,205,0,130,75,88,38,182,6,83,18,69,202,169,18]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"enc":{"type":0,"key":{"buffer":{"type":"Buffer","data":[48,89,48,19,6,7,42,134,72,206,61,2,1,6,8,42,134,72,206,61,3,1,7,3,66,0,4,117,196,250,102,102,249,39,125,100,98,204,38,126,53,173,17,161,114,125,253,187,76,230,129,127,117,137,83,254,45,39,51,69,42,31,69,118,78,244,61,237,74,28,90,111,171,145,232,202,176,104,12,98,2,219,113,249,177,211,171,236,161,156,146]},"offset":0,"markedOffset":-1,"limit":91,"littleEndian":false,"noAssert":false}},"sig":null}  +0ms
E1228 17:48:59.889240000 123145307131904 handshake.c:128] Security handshake failed: {"created":"@1482927539.889209000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1482927539.889156000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}
E1228 17:48:59.890431000 123145307131904 completion_queue.c:254] Operation failed: tag=0x102201500, error={"created":"@1482927539.890382000","description":"Failed to create subchannel","file":"../src/core/ext/client_config/subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482927539.890296000","description":"Pick Cancelled","file":"../src/core/ext/lb_policy/pick_first/pick_first.c","file_line":170}]}
E1228 17:48:59.890538000 123145307131904 completion_queue.c:254] Operation failed: tag=0x10220c9f0, error={"created":"@1482927539.890382000","description":"Failed to create subchannel","file":"../src/core/ext/client_config/subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482927539.890296000","description":"Pick Cancelled","file":"../src/core/ext/lb_policy/pick_first/pick_first.c","file_line":170}]}
E1228 17:48:59.890660000 123145307131904 completion_queue.c:254] Operation failed: tag=0x1017078f0, error={"created":"@1482927539.890382000","description":"Failed to create subchannel","file":"../src/core/ext/client_config/subchannel_call_holder.c","file_line":185,"referenced_errors":[{"created":"@1482927539.890296000","description":"Pick Cancelled","file":"../src/core/ext/lb_policy/pick_first/pick_first.c","file_line":170}]}
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error
    at ClientDuplexStream._emitStatusIfDone (/Users/goupadhy/work/src/github.com/goupadhy/SDK-Demo/node_modules/grpc/src/node/src/client.js:189:19)
    at ClientDuplexStream._readsDone (/Users/goupadhy/work/src/github.com/goupadhy/SDK-Demo/node_modules/grpc/src/node/src/client.js:158:8)
    at readCallback (/Users/goupadhy/work/src/github.com/goupadhy/SDK-Demo/node_modules/grpc/src/node/src/client.js:217:12)

**Comment by goupadhy** [comment]
Node version v4.4.5

**Comment by goupadhy** [comment]
I was able to get it work sometime yesteryday, post that its the same. I tried to recreate the issue to find the fix but Getting error when i'm trying to run the sample.

**Comment by mastersingh24** [comment]
so I was actually able to reproduce the error myself.  I then ran the demo again after I got the error and things seemed to work fine.  I believe the issue is with the eventHub but need to see if I can do some further debugging.

**Comment by mastersingh24** [comment]
so I have only been able to reproduce this once so far - may have to create a new network and try again

**Comment by goupadhy** [comment]
I just downloaded sample again on my MAC machine and ran the sample with the Blockchain service credentials as suggested in the documentation section. But every time it throws Security handshake failed error or failed to enroll admin : Error: Identity or token does not match.

**Comment by mastersingh24** [comment]
If you are using the same Blockchain service instance as before, the issue is going to be that user "admin" was previously enrolled and enrollment uses a one-time password so it will definitely fail.

You can try changing this line:   https://github.com/IBM-Blockchain/SDK-Demo/blob/master/helloblockchain.js#L134

You can change `users[0]` to `users[1]` in that line to get past the enroll error.  I think you'll just need to re-run the sample if you get the secure handshake error.

**Comment by mastersingh24** [comment]
you can also just comment out all of the various "eventHub" lines in the code as well since I believe it is the root cause of the secure handshake error(s)

**Comment by mastersingh24** [comment]
I'm going to attempt an interim fix by dealing with the unhandled error(s) coming back from connection to eventHub

**Comment by mrshah-at-work** [comment]
@goupadhy I tried it multiple times on a machine with node `v6.9.2` and npm version `3.10.9`. We have seen issues with hfc & nodejs versions older than 6.9 before. Can you try updating the node version and let us know if it works?

**Comment by goupadhy** [comment]
Some times it works and some time it doesn't. It is working as expected now. Thanks for all the help!

**Comment by mastersingh24** [comment]
going to close this for now.  let us know if there are any more issues

**Comment by jonathan-yk-tan** [comment]
@mastersingh24 I have tried changing the line in the js code as you advised from users[0] to users[1] , this got passed the handshake error, does this mean the original "admin" user was not meant to be "re-enrolled" ?

**Comment by mrshah-at-work** [comment]
@jonathan-yk-tan you cannot "re-enroll" *any user*. Once you enroll the user, the membership service sends enrollment certificate and removes the user from the database. Thus, you cannot re-enroll the user but you can re-use the enrollment certificate that was received the first time.
