### ISSUE TITLE
Failed to Deploy

### ISSUE THREAD

**Issue by Yuanyoo** [IBM-Blockchain/SDK-Demo#22]
I`m having this error:
Failed to deploy chaincode: request={"fcn":"init","args":["a","100","b","200"],"chaincodePath":"chaincode","certificatePath":"/certs/peer/cert.pem"}, error={"error":{},"msg":"Error: Error creating deployment archive [/tmp/deployment-package.tar.gz]: Error: Error on fs.createWriteStream"}

Can someone help me pls?

**Comment by Yuanyoo** [comment]
I`ve just solved the WriteStream error but i`m still getting this:
Failed to deploy chaincode: request={"fcn":"init","args":["a","100","b","200"],"chaincodePath":"chaincode","certificatePath":"/certs/peer/cert.pem"}, error="timed out waiting for transaction to complete"

**Comment by mastersingh24** [comment]
@Yuanyoo - are you running this against a Bluemix Blockchain starter network?

**Comment by Yuanyoo** [comment]
Yeah, I fixed this problem by following:
https://developer.ibm.com/answers/questions/323782/blockchain-hfc-sdk.html?page=2&pageSize=10&sort=votes&smartspace=urbancode
Changing my branch to:
git checkout b7d5195
Thanks anyway! I hope this can help someone else who comes up with this problem on windows

**Comment by mrshah-at-work** [comment]
Thanks @Yuanyoo for sharing the solution, I will close this issue as it is resolved.
